### ISSUE TITLE
Error in matlab

### ISSUE THREAD

**Issue by LeeTsinghua** [luyongxi/az-net#4]
hi@luyongxi
I am a student in Tsinghua University and I am doing a research on your project. 
The problem is that after training the datasets, the voc_eval_cls.m could not properly work. Here is the error screenshot.
![problem](https://cloud.githubusercontent.com/assets/16276672/21394016/ccd47ecc-c7d1-11e6-8d4e-49af682f6465.PNG)

I will appreciate it if you can give me any advice. Thank you.

**Comment by luyongxi** [comment]
Hi @LeeTsinghua,

It seems that your voc dataset is missing some annotation files. I am closing this issue as it is not related to AZ-Net codes. 

Yongxi
