### ISSUE TITLE
how is the Zoom-indicator trained during training？

### ISSUE THREAD

**Issue by Huangswust182** [luyongxi/az-net#6]
Hello, Thank you for your source code.
I'd like to ask you a question. how is the Zoom-indicator trained during training and how is the threshold of Zoom-indicator determined? How does iteratively dividing regions work? Mainly I did not find the corresponding code in the source code.
Thank you very much if you can answer my question！

**Comment by luyongxi** [comment]
For zoom indicator training targets, please see https://github.com/luyongxi/az-net/blob/master/lib/az_data_layer/roidb.py#L313. 

The threshold is determined by validation. 

The iterative dividing works as a recursion. Please see https://github.com/luyongxi/az-net/blob/master/lib/detect/test.py#L189 for the testing procedure.

**Comment by Huangswust182** [comment]
Thank you very much
